const dataProduct = [
  {
    id: 1,
    name: "Sterling by Music Man Saint Vincent Goldie",
    price: 15000,
    quantity: 2,
    type: "guitar",
    imageURL: [],
    sound: "",
    description: {
      product: "Sterling by Music Man Saint Vincent Goldie",
      brand: "Sterling",
      series: "Saint Vincent Goldie",
      color: "Cashmere (CSH), Velveteen (VLT)",
      note: "",
    },
  },
  {
    id: 2,
    name: "Sterling by Music Man Saint Vincent Goldie",
    price: 15000,
    quantity: 2,
    type: "guitar",
    imageURL: [],
    sound: "",
    description: {
      product: "Sterling by Music Man Saint Vincent Goldie",
      brand: "Sterling",
      series: "Saint Vincent Goldie",
      color: "Cashmere (CSH), Velveteen (VLT)",
      note: "",
    },
  },
  {
    id: 3,
    name: "Sterling by Music Man Saint Vincent Goldie",
    price: 15000,
    quantity: 2,
    type: "guitar",
    imageURL: [],
    sound: "",
    description: {
      product: "Sterling by Music Man Saint Vincent Goldie",
      brand: "Sterling",
      series: "Saint Vincent Goldie",
      color: "Cashmere (CSH), Velveteen (VLT)",
      note: "",
    },
  },
  {
    id: 4,
    name: "Sterling by Music Man Saint Vincent Goldie",
    price: 15000,
    quantity: 2,
    type: "guitar",
    imageURL: [],
    sound: "",
    description: {
      product: "Sterling by Music Man Saint Vincent Goldie",
      brand: "Sterling",
      series: "Saint Vincent Goldie",
      color: "Cashmere (CSH), Velveteen (VLT)",
      note: "",
    },
  },
  {
    id: 5,
    name: "Sterling by Music Man Saint Vincent Goldie",
    price: 15000,
    quantity: 2,
    type: "guitar",
    imageURL: [],
    sound: "",
    description: {
      product: "Sterling by Music Man Saint Vincent Goldie",
      brand: "Sterling",
      series: "Saint Vincent Goldie",
      color: "Cashmere (CSH), Velveteen (VLT)",
      note: "",
    },
  },
  {
    id: 6,
    name: "Sterling by Music Man Saint Vincent Goldie",
    price: 15000,
    quantity: 2,
    type: "guitar",
    imageURL: [],
    sound: "",
    description: {
      product: "Sterling by Music Man Saint Vincent Goldie",
      brand: "Sterling",
      series: "Saint Vincent Goldie",
      color: "Cashmere (CSH), Velveteen (VLT)",
      note: "",
    },
  },
  {
    id: 7,
    name: "Sterling by Music Man Saint Vincent Goldie",
    price: 15000,
    quantity: 2,
    type: "guitar",
    imageURL: [],
    sound: "",
    description: {
      product: "Sterling by Music Man Saint Vincent Goldie",
      brand: "Sterling",
      series: "Saint Vincent Goldie",
      color: "Cashmere (CSH), Velveteen (VLT)",
      note: "",
    },
  },
  {
    id: 8,
    name: "Sterling by Music Man Saint Vincent Goldie",
    price: 15000,
    quantity: 2,
    type: "guitar",
    imageURL: [],
    sound: "",
    description: {
      product: "Sterling by Music Man Saint Vincent Goldie",
      brand: "Sterling",
      series: "Saint Vincent Goldie",
      color: "Cashmere (CSH), Velveteen (VLT)",
      note: "",
    },
  },
];

module.exports = dataProduct;
