const dataProduct = [
  
      {
        id: 1,
        name: "Yamaha F310",
        price: 4290,
        quantity: 9,
        type: "guitar",
        imageURL: "G1.png",
        sound: "guitar.mp3",
        description: {
          product:
            "This Yamaha acoustic guitar is considered the best-selling top hit model of all time. With a design that has a standard design and fits every body. Because it is a Japanese brand guitar, it is specially designed for Asian people. The body is comfortable to hold It also has a black glossy edge trim that makes the body stand out even more. As for the sound of this model, it is resonant, so it is suitable for people who like to play chords and are very beginners as it is a Yamaha brand that produces a wide range of musical instruments. Therefore, you can be confident about the quality that is definitely worth the price.",
          brand: "Yamaha",
          series: "Yamaha F310",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 2,
        name: "Fender CD60s",
        price: 7600,
        quantity: 9,
        type: "guitar",
        imageURL: "G2.png",
        sound: "guitar.mp3",
        description: {
          product:
            "If talking about the brand Fender, many people who are experienced in the guitar industry will probably hear this name often. This model of Fender acoustic guitar is very popular, whether beginners or seasoned pros. The material used to make the body is considered high quality wood. causing the price to be a little too strong But the sound received is worth the price paid. Especially the use of mahogany contributes to making the sound soft. Soft and has dimensions as well. The two-way swivel neck brace allows for more freedom in adjusting the touching.",
          brand: "Fender",
          series: "Fender CD60s",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 3,
        name: "Taylor Baby Taylor/BT1",
        price: 13300,
        quantity: 9,
        type: "guitar",
        imageURL: "G3.png",
        sound: "guitar.mp3",
        description: {
          product:
            "Anyone who is looking for a mini guitar that can be used for a long time without having to change it often, recommend this Taylor Baby BT1 model, if anyone who has a budget can arrange this model. Because in addition to having a compact size, easy to carry, the sound of this model is also unique in that it has a clear, resonant sound. Plus, the back and sides of the wood are African mahogany that will help clear the treble. The resonance and clear treble mixed out in this Taylor Baby is perfect. This model can be considered as a mini model whose quality is beyond the price.",
          brand: "Taylor",
          series: "Taylor Baby Taylor/BT1",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 4,
        name: "Crafter HD-200CE",
        price: 6800,
        quantity: 9,
        type: "guitar",
        imageURL: "G4.png",
        sound: "guitar.mp3",
        description: {
          product:
            "This body model is very eye-catching. Both design and shape Everything seems to fit together. Crafter is an acoustic guitar from Korea that is popular among guitar players. The body material is spruce and mahogany. Resulting in a sound that is as soft as a top guitar and comes at a lovely price, but with good grade materials, it is not surprising that this brand of guitar is popular with both beginners and professionals. In addition, in the CR-T NV model, there is also a built-in mini LCD tuner.",
          brand: "Crafter",
          series: "Crafter HD-200CE",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 5,
        name: "Gusta GD130",
        price: 5940,
        quantity: 9,
        type: "guitar",
        imageURL: "G5.png",
        sound: "guitar.mp3",
        description: {
          product:
            "Dreadnought style acoustic guitar, another popular brand among beginners as well. In addition to the body, it is composed of a whole piece of Sitka spruce. The wood on the sides and back is still rosewood that makes the sound of the guitar when played out be thick and soft. There is also an added matte coating. In case when playing, it can be handled easily and does not slip easily, making it considered another model that can be used from beginners to professionals who have to go to work often as well.",
          brand: "Gusta",
          series: "Gusta GD130",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 6,
        name: "Kazuki Deluxe DLKZ-41C",
        price: 15000,
        quantity: 9,
        type: "guitar",
        imageURL: "G6.png",
        sound: "guitar.mp3",
        description: {
          product:
            "A beginner who is learning to play an acoustic guitar who is looking for a pocket-friendly price. We recommend this Kazuki acoustic guitar. The body of this model is also basswood with good bass sound. clear thick soundtrack Makes it easier to play strum chords or fingerstyle, it's very comfortable. Plus cutting the ABS binding edge with white and using a black pick to draw patterns. This makes this body look more beautiful than the price. In addition, this model also has other colors to choose from. Whether it is Natural, Sun Burst, Black and Wine Red.",
          brand: "Kazuki Deluxe",
          series: "Kazuki Deluxe DLKZ-41C",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 7,
        name: "Martin LX1",
        price: 14700,
        quantity: 9,
        type: "guitar",
        imageURL: "G7.png",
        sound: "guitar.mp3",
        description: {
          product:
            "For vintage people who like to play acoustic music. Like a luxurious guitar with a full budget, this Martin LX1 acoustic guitar will be the answer for your friends. This brand of guitar is also a brand that artists around the world choose to use. Due to the size suitable for carrying on a trip And the body itself is also made of high-pressure mahogany. makes the body very durable The resulting sound still gives a country feel. If anyone who is this line guarantees that this model is worth the investment in the long run.",
          brand: "Martin",
          series: "Martin LX1",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 8,
        name: "Epiphone EJ-200SCE",
        price: 15300,
        quantity: 9,
        type: "guitar",
        imageURL: "G8.png",
        sound: "guitar.mp3",
        description: {
          product:
            "The legendary guitar brand that has been around since 1973 and is the guitar that many world-renowned artists use, such as Elvis Presley or Bob Dylan, which is considered a world-class classic brand. can The body is made of maple wood, so the sound of this guitar is clear. deep chimes Focuses on playing chords or fingerstyle very well. The color of the knobs and crown inlays give the guitar a more distinctive character that is typical of Epiphone classical guitars, making this model a collector's item. It is also suitable for people who like a jumbo body shape.",
          brand: "Epiphone",
          series: "Epiphone EJ-200SCE",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 9,
        name: "Enya EMX1EQ",
        price: 4680,
        quantity: 9,
        type: "guitar",
        imageURL: "G9.png",
        sound: "guitar.mp3",
        description: {
          product:
            "This guitar has a wood body that is more exotic than other models. Because this model is an orchestra model, it is compact and suitable for children as well. The Enya acoustic guitar also has a body made of Koe wood that has undergone a high-pressure baking process. The matt-patterned body reveals the clear grain of the wood. With a small shape plus a matte body coating Makes the grip time not slip easily if sweating. But caution is to avoid storing guitars in hot and humid climates. because it will affect the guitar, causing it to deteriorate faster",
          brand: "Epiphone",
          series: "Enya EMX1EQ",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 10,
        name: "Gusta GJB5-05",
        price: 10170,
        quantity: 9,
        type: "bass",
        imageURL: "B1.jpeg",
        sound: "bass.mp3",
        description: {
          product:
            "5-string bass with active strength that comes with a tangible price. And this model will have a variety of material upgrades starting with an ash body, Canadian Roasted Maple neck, as well as a beautiful wood fingerboard, nut bone, and D'addario EXL 165-5 strings for a 5-string bass. The pickup is adapted to use the K-Calss JB Bass model, giving better sound quality than ever. The assembly work is better than the price, anyone who likes Active Bass, this model is difficult to refuse.",
          brand: "Gusta",
          series: "Gusta GJB5-05",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 11,
        name: "Yamaha TRBX174 ",
        price: 8100,
        quantity: 9,
        type: "bass",
        imageURL: "B2.jpeg",
        sound: "bass.mp3",
        description: {
          product:
            "Yamaha TRBX174 bass, basic model, affordable price and get complete usage The body is mahogany that produces a good bass tone. Maple neck, clear midrange Rosewood Fingerboard This model comes with 2 Split Single Coil / Ceramic pickups, comes with a separate volume button for each pickup and a tone control knob, whether it's strum or slap. famous brand The design will be modern. Anyone looking for a good starter bass with a neat sound Come try this model and you will like it.",
          brand: "Yamaha",
          series: "Yamaha TRBX174",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 12,
        name: "Cort C4 Plus ZBMH  ",
        price: 9775,
        quantity: 9,
        type: "bass",
        imageURL: "B3.jpeg",
        sound: "bass.mp3",
        description: {
          product:
            "Sleek, beautiful, elegant, these are the three words that describe this Cort C4 Plus ZBMH very well. With an incredibly cheap price with a Hi-End bass design like this, it's still worth it. Mahogany body with maple and zebra wood tops, clear wood grain, giving it a distinctive vintage look. The neck is also made of Canadian maple, a solid wood family, giving a thick sound. making the sound come out absolutely satisfying",
          brand: "Cort",
          series: "Cort C4 Plus ZBMH",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 13,
        name: "Sire Marcus Miller M2DX  ",
        price: 9450,
        quantity: 9,
        type: "bass",
        imageURL: "b4.jpeg",
        sound: "bass.mp3",
        description: {
          product:
            "The Sire Marcus Miller M2DX electric bass is the signature bass of Marcus Miller, renowned jazz bassist, composer and producer. Comes in the most intense form with bright tones. This model is a DX model which uses a maple top, unlike the M2, which has a mahogany body only. Makes it, in addition to getting beautiful and eye-catching wood grain The sound also has a more pleasing dimension.",
          brand: "Sire Marcus",
          series: "Sire Marcus Miller M2DX ",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 14,
        name: "Squier Affinity PJ Bass",
        price: 8350,
        quantity: 9,
        type: "bass",
        imageURL: "B5.jpeg",
        sound: "bass.mp3",
        description: {
          product:
            "This Squier Affinity PJ Bass has two single-coil pickups that come in different styles. which, if you like a jazz sound, can be adjusted to be an intermediate pickup Or if anyone likes a tight sound, choose a bridge pickup. which is considered a perfect combination Beautifully designed The wood material used is a good grade, both the elder body and the maple neck. considered worth more than the price",
          brand: "Squier Affinity PJ Bass",
          series: "Squier Affinity PJ Bass ",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 15,
        name: "Ibanez TMB35",
        price: 9000,
        quantity: 9,
        type: "bass",
        imageURL: "B6.jpeg",
        sound: "bass.mp3",
        description: {
          product:
            "The Ibanez TMB35 is a good 5-string bass in the Talman series. This model will have a scale length of only 30 inches, easy to play, suitable for small people or those who do not like long bass. The sound is comfortable. No worries. Clear mids from a poplar body, maple neck, and Jabo fingerboard. Two pickups are available, the Dynamix P/J, giving the Talman Bass an impressive range of tones. From strong rock tones to intense R&B. It's got it all. Classic looks and modern flair. It is another model that is so good that it has to be recommended.",
          brand: "Ibanez",
          series: "Ibanez TMB35",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 16,
        name: "Schecter SGR C-4",
        price: 9775,
        quantity: 9,
        type: "bass",
        imageURL: "B7.jpeg",
        sound: "bass.mp3",
        description: {
          product:
            "The Schecter SGR C-4 is a standard 4-string bass with a sleek black finish from Schecter's sub-brand, SGR, which is known for its rock-and-roll instruments. until the metal This bass model is also the same, starting from the sleek exterior, including the coating of all materials on the bass body to be black, pleasing to the rock people. The body is made of basswood mixed with an ash face covering for a well-balanced sound that isn't too thick and clear. The neck is made of maple wood, just like the typical Hi-end grade bass. The character of the middle sound is clear.",
          brand: "Schecter",
          series: "Schecter SGR C-4",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 17,
        name: "Ibanez GSR200B",
        price: 9900,
        quantity: 9,
        type: "bass",
        imageURL: "B8.jpeg",
        sound: "bass.mp3",
        description: {
          product:
            "The Ibanez GSR200B is a 4-string bass that is sleek and elegant. Enyoto wooden body Beautiful, see the wood pattern, maple neck, Jatoba fingerboard, beautiful and strange, the sound bounces clearly. It comes with a Dynamix P neck pickupPassive and a Dynamix J bridge pickupPassive. Can play all music genres with Phat II EQ EQ adjustment. The design and parts are as good as a famous brand. Compared to the price, I can say that it is very worthwhile.",
          brand: "Ibanez",
          series: "Ibanez GSR200B",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 18,
        name: "Squier Jazz Bass",
        price: 9900,
        quantity: 9,
        type: "bass",
        imageURL: "B9.jpeg",
        sound: "bass.mp3",
        description: {
          product:
            "The Squier Jazz Bass comes with a beautiful shape in a jazz style. The woodwork is meticulously detailed, using poplar wood that produces a grainy sound. Not too opaque, so it's suitable for jazz music that has to walk bass all the time. This model is guaranteed to have fun walking. The wide frets are hard to miss. The pickups are two single-coil with two separate volume controls and master volume. This makes it possible to combine the sound of both pickups perfectly for a variety of music genres to use. It can be called a versatile bass in a jazz style.",
          brand: "Squier Jazz Bass",
          series: "Squier Jazz Bass",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 19,
        name: "Yamaha P-125",
        price: 29900,
        quantity: 9,
        type: "piano",
        imageURL: "P1.jpeg",
        sound: "piano.mp3",
        description: {
          product:
            "Yamaha P-125, a new electric piano from Yamaha, is a model developed from the P-115. The added feature is that it can set up to 24 presets from the original P-115 that could do 14 voices and can play more rhythms. From 14 to 20 rhythms, as well as adding demo songs to listen to 21 songs from the original 14 songs, adding music to 24 satisfying sounds, and the speakers are also adjusted to a new 2-way format with the same cool function. Still for both professional musicians and beginners. Whether it's a keyboard Realistic Graded Hammer Standard (GHS) hammer system with 4 weights Soft, Medium, Hard and Fixed. Sound varies according to the mood of the song.",
          brand: "Yamaha P-125",
          series: "Yamaha",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 20,
        name: "Yamaha P-125",
        price: 29900,
        quantity: 9,
        type: "piano",
        imageURL: "P2.jpeg",
        sound: "piano.mp3",
        description: {
          product:
            "Yamaha P-125, a new electric piano from Yamaha, is a model developed from the P-115. The added feature is that it can set up to 24 presets from the original P-115 that could do 14 voices and can play more rhythms. From 14 to 20 rhythms, as well as adding demo songs to listen to 21 songs from the original 14 songs, adding music to 24 satisfying sounds, and the speakers are also adjusted to a new 2-way format with the same cool function. Still for both professional musicians and beginners. Whether it's a keyboard Realistic Graded Hammer Standard (GHS) hammer system with 4 weights Soft, Medium, Hard and Fixed. Sound varies according to the mood of the song.",
          brand: "Yamaha",
          series: "Yamaha P-125",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 21,
        name: "Kawai KDP75 Digital Piano",
        price: 32500,
        quantity: 9,
        type: "piano",
        imageURL: "P3.jpeg",
        sound: "piano.mp3",
        description: {
          product:
            "The Kawai KDP75 Digital Piano offers great grand piano touch and tone at an affordable price. It comes in an 88-key Responsive Hammer Compact model that includes Kawai's famous Shigeru Kawai SK-EX grand piano sound. The sound system will simulate stereo sound from Harmonic Imaging for a realistic sound with dimensions. The weight of the hammer differs, with the bass side being heavier than the treble side. Giving a more realistic feeling of playing",
          brand: "Kawai",
          series: "Kawai KDP75 Digital Piano",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 22,
        name: "Coleman F107",
        price: 11800,
        quantity: 9,
        type: "piano",
        imageURL: "P4.jpeg",
        sound: "piano.mp3",
        description: {
          product:
            "The Coleman F107 electric piano is ideal for those looking for an affordable electric piano. But get all the basic functions Because this model will have a maximum of 88 keys to support a wider range of music notes. Responds to almost every genre of music with 8 built-in tones With 128 more rhythms, it can be used for both personal practice or can be played live and recorded as you like. because it can be connected to a computer",
          brand: "Coleman",
          series: "Coleman F107",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 23,
        name: "Coleman F201",
        price: 13900,
        quantity: 9,
        type: "piano",
        imageURL: "P5.jpeg",
        sound: "piano.mp3",
        description: {
          product:
            "Coleman F201, a quality electric piano at a great price from the Coleman brand, Model F201, The France DREAM5 Series 5504 sound source, has a sound that is closer to a grand piano, comes in a 88-key format, with the keys being a Hammer Action system that Realistic with 380 built-in tones Supports all music genres and 128 rhythms that can be used for practicing or recording music. The speaker is a Hi-Fi Full-Band 3D Stereo High-Power Speaker [15 watts] with a clear sound like playing live in a studio. Or if you want to practice privately, you can also connect headphones.",
          brand: "Coleman",
          series: "Coleman F201",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 24,
        name: "Casio PX-S1100",
        price: 28900,
        quantity: 9,
        type: "piano",
        imageURL: "P6.jpeg",
        sound: "piano.mp3",
        description: {
          product:
            "Casio PX-S1100, the ever-evolving electric piano Sleek, distinctive design that fits in any space with hammer mechanism At just 232mm deep, it fits in your living room, bedroom or anywhere else, with touch controls giving it a futuristic look. True to the sound and playability of a grand piano, the Privia PX-S1100 speaker system features a stronger diaphragm for cleaner, high-end sound. more complete and an improved internal structure design for a more dynamic low end. The result is a well-balanced sound with a clear feel.Coleman F201, a quality electric piano at a great price from the Coleman brand, Model F201, The France DREAM5 Series 5504 sound source, has a sound that is closer to a grand piano, comes in a 88-key format, with the keys being a Hammer Action system that Realistic with 380 built-in tones Supports all music genres and 128 rhythms that can be used for practicing or recording music. The speaker is a Hi-Fi Full-Band 3D Stereo High-Power Speaker [15 watts] with a clear sound like playing live in a studio. Or if you want to practice privately, you can also connect headphones.",
          brand: "Casio",
          series: "Casio PX-S1100",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 25,
        name: "Coleman F401BT",
        price: 18900,
        quantity: 9,
        type: "piano",
        imageURL: "P7.jpeg",
        sound: "piano.mp3",
        description: {
          product:
            "Coleman F401BT Electric piano, fully functional, from the Coleman brand that used to produce many models of inexpensive pianos. For this model, the first highlight that is seen is that it will be a Bluetooth connection, can be used as a back track or easily record music. And it also supports MP3 files by connecting via USB as well. Multi-function LCD Blu-ray digital display screen, easy to control with fingertips. The sound is as good as other famous brands because it uses the sound source The France DREAM5 Series 5504, giving a realistic sound like a grand piano.",
          brand: "Coleman",
          series: "Coleman F401BT",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 26,
        name: "Yamaha P45",
        price: 18900,
        quantity: 9,
        type: "piano",
        imageURL: "P8.jpeg",
        sound: "piano.mp3",
        description: {
          product:
            "Yamaha P45 Electric piano, fully functional, from the Yamaha P45 brand that used to produce many models of inexpensive pianos. For this model, the first highlight that is seen is that it will be a Bluetooth connection, can be used as a back track or easily record music. And it also supports MP3 files by connecting via USB as well. Multi-function LCD Blu-ray digital display screen, easy to control with fingertips. The sound is as good as other famous brands because it uses the sound source The France DREAM5 Series 5504, giving a realistic sound like a grand piano.",
          brand: "Yamaha",
          series: "Yamaha P45",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 27,
        name: "NUX WK-310",
        price: 20900,
        quantity: 9,
        type: "piano",
        imageURL: "P9.jpeg",
        sound: "piano.mp3",
        description: {
          product:
            "NUX WK-310 Entry-level electric piano It gives you the ultimate piano playing feel with 5 levels of grand piano sounds recorded with 5-Level Dynamic Stereo Piano Sampling and Hammer-Action keys. With 4 dynamic curves, the weight is similar to that of a true grand piano.",
          brand: "NUX",
          series: "NUX WK-310",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 28,
        name: "Hofner H5G",
        price: 18000,
        quantity: 9,
        type: "violin",
        imageURL: "V1.jpeg",
        sound: "",
        description: {
          product:
            "When it comes to the most popular brand of violins. Everyone thinks of the German Hofner violin. Because it is unique and good quality according to Hofner standards. It is also made from good quality grade A wood coated with golden brown lacquer. Make it look elegant and expensive. In addition, the shop also has both made in Germany. And made in China to choose according to the desired quality and price.",
          brand: "Hofner",
          series: "Hofner H5G",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 29,
        name: "Sandner 306 - SV6",
        price: 7000,
        quantity: 9,
        type: "violin",
        imageURL: "V2.jpeg",
        sound: "",
        description: {
          product:
            "A well-known brand of violin made by a skilled German craftsman. This gives the violin the quality and uniqueness of Germany, which is famous for violin production. The front of the violin is made of spruce. The back is made of maple wood. both of which are considered good quality woods that are widely used to make violins. In addition, the craftsman also fine-tuned the appearance and thickness of the wood panels of this violin. in order to create the most beautiful sound Players can be confident that they will receive a violin with a beautiful sound and good quality.",
          brand: "Sandner",
          series: "Sandner 306 - SV6",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 30,
        name: "YAMAHA V5SA",
        price: 14900,
        quantity: 9,
        type: "violin",
        imageURL: "V3.png",
        sound: "",
        description: {
          product:
            "This brand of violin is a brand that is widely popular both in Thailand and abroad. Therefore, it is guaranteed that the violin will definitely meet the quality standards of the YAMAHA brand. This model is suitable for players of all levels. Whether it's beginner, intermediate or advanced, the violin is made of good quality spruce and maple. There is also a 12-month warranty and a complete range of accessories for buyers. Whether it's a violin bow Good quality violin case and pine resin.",
          brand: "YAMAHA",
          series: "YAMAHA V5SA",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 31,
        name: "Elman EL100",
        price: 5490,
        quantity: 9,
        type: "violin",
        imageURL: "V4.jpeg",
        sound: "",
        description: {
          product:
            "This brand of violin is suitable for people who want to practice playing classical music. Because when playing the violin, it produces a sweet, clear, melodious sound, and can play both high and low sounds as well. In addition, the violin is made from real grade A wood. It's an excellent material. It is also available in four different sizes, giving players the opportunity to choose the right size violin for themselves. make the play effective and play more comfortably And most importantly, this shop has many accessories, including a moisture meter as well.",
          brand: "Elman",
          series: "Elman EL100",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 36,
        name: "YAMAHA V3SKA",
        price: 10400,
        quantity: 9,
        type: "violin",
        imageURL: "V5.png",
        sound: "",
        description: {
          product:
            "A popular brand of violin that is internationally recognized for its excellent quality. This model is therefore suitable for beginners who want a well-known brand of violin",
          brand: "YAMAHA",
          series: "YAMAHA V3SKA",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 32,
        name: "Nakovitz VN110",
        price: 5050,
        quantity: 9,
        type: "violin",
        imageURL: "V6.jpeg",
        sound: "",
        description: {
          product:
            "The most popular violin brand for beginner violin players. which is made from quality wood In addition, the various parts of the violin are well assembled. making it possible to actually use In addition, the shop also provides free gifts that are accessories for full-heavy violins. Whether it's a violin case Violin bows and pine resin, as well as a violin cleaning cloth. And the equalizer and percussion are included as well, very worthwhile.",
          brand: "Nakovitz",
          series: "Nakovitz VN110",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 33,
        name: "SYNWIN SV441005",
        price: 4900,
        quantity: 9,
        type: "violin",
        imageURL: "V7.jpeg",
        sound: "",
        description: {
          product:
            "SYNWIN brand violin is a brand from Singapore. through the selection of YAMAHA, the world's leading musical instrument brand This brand of violin is a quality violin. Made from good quality wood make a beautiful sound It is also the most affordable in the YAMAHA group, making it ideal for beginners who want to find a good quality violin to start practicing with. Additional accessories are also available, and the violin is varnished at no extra charge.",
          brand: "SYNWIN",
          series: "SYNWIN SV441005",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 34,
        name: "Overtone OV150",
        price: 2200,
        quantity: 9,
        type: "violin",
        imageURL: "V8.jpeg",
        sound: "",
        description: {
          product:
            "Another affordable violin option that's perfect for beginners. It is also made from good quality real wood. And unique in the design of the bridge, which is one of the elements of the violin. Makes the violin easy to play Can play in many genres Whether it's a classic, sweet melody or a country style, it can be played as well. There are also 5 sizes to choose from, so players can choose the right fit and fit for themselves. And most importantly, the shop has a warranty for up to 1 year as well.",
          brand: "Overtone",
          series: "Overtone OV150",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 35,
        name: "Overtone OV150",
        price: 2200,
        quantity: 9,
        type: "violin",
        imageURL: "V9.jpeg",
        sound: "",
        description: {
          product:
            "Another affordable violin option that's perfect for beginners. It is also made from good quality real wood. And unique in the design of the bridge, which is one of the elements of the violin. Makes the violin easy to play Can play in many genres Whether it's a classic, sweet melody or a country style, it can be played as well. There are also 5 sizes to choose from, so players can choose the right fit and fit for themselves. And most importantly, the shop has a warranty for up to 1 year as well.",
          brand: "Overtone",
          series: "Overtone OV150",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 37,
        name: "Gusta First Touring",
        price: 8900,
        quantity: 9,
        type: "drum",
        imageURL: "D1.jpeg",
        sound: "drum.mp3",
        description: {
          product:
            "An affordable drum set with excellent quality. The drum body is made of poplarwood 6ply for a clearer sound. Comes with a drum set edge The main drum set is well thick chromed. Which gives it a nice look as well as good durability, and the Gusta First Touring adds quite a large number of drumsticks so you can set up the drums more precisely according to your own style. It also comes with Hardware, Cymble, which can be called a single set, can be practiced and played in the studio.",
          brand: "Gusta First Touring",
          series: "Gusta First Touring",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 38,
        name: "Overdrive",
        price: 8900,
        quantity: 9,
        type: "drum",
        imageURL: "D2.jpeg",
        sound: "drum.mp3",
        description: {
          product:
            "A drum set made by Thai people. It is a good quality drum set with 5 standard size drums. It is made of high quality wood. The hardware is durable. The edge of the drum is chrome plated to add beauty and coolness. durability A very suitable drum for beginners to play drums.",
          brand: "Overdrive",
          series: "Overdrive",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 39,
        name: "Gusta Premier",
        price: 9900,
        quantity: 9,
        type: "drum",
        imageURL: "D3.jpeg",
        sound: "drum.mp3",
        description: {
          product:
            "Gusta Premier that comes with Hardware & Cymble is not enough, there is also a Remo drum skin, a drum skin that every drummer knows and is popular all over the world. If you've read up to here, Music Arms will tell you that we can give you all this for less than ten thousand baht. Yes, you heard it right, you can take all of this for less than ten thousand baht.",
          brand: "Gusta Premier",
          series: "Gusta Premier",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 40,
        name: "Mapex Prodigy",
        price: 13900,
        quantity: 9,
        type: "drum",
        imageURL: "D4.jpeg",
        sound: "drum.mp3",
        description: {
          product:
            "Presenting Mapex Prodigy, a complete 5-piece drum set that comes with Hardware, Cymble. The drum body is made of Basswood 9ply that gives your sound a thick, resonant tone. More than that, this drum set also comes Comes with Remo drum skins as well, suitable for drum set beginners.",
          brand: "Mapex Prodigy",
          series: "Mapex Prodigy",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 41,
        name: "Mapex Prodigy",
        price: 13900,
        quantity: 9,
        type: "drum",
        imageURL: "D5.jpeg",
        sound: "drum.mp3",
        description: {
          product:
            "Presenting Mapex Prodigy, a complete 5-piece drum set that comes with Hardware, Cymble. The drum body is made of Basswood 9ply that gives your sound a thick, resonant tone. More than that, this drum set also comes Comes with Remo drum skins as well, suitable for drum set beginners.",
          brand: "Mapex Prodigy",
          series: "Mapex Prodigy",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 42,
        name: "Ludwig Accent Series ",
        price: 15300,
        quantity: 9,
        type: "drum",
        imageURL: "D6.jpeg",
        sound: "drum.mp3",
        description: {
          product:
            "The Ludwig Accent Series is a built-in drum set that has everything you need and doesn't cost anything extra. Make a drum body from Poplar wood 9ply / 8 mm that makes the sound you hit have a resonance, but with clarity, along with a 45-degree Bearing Edge for a thicker, clearer sound, along with full Hardware, Cymble, allowing you to Have fun practicing your drums. Hit the music style you want. This drum kit is perfect for laying the groundwork for your career as a professional drummer.",
          brand: "Ludwig Accent Series ",
          series: "Ludwig Accent Series ",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 43,
        name: "Cmc Indy Series",
        price: 18500,
        quantity: 9,
        type: "drum",
        imageURL: "D7.jpeg",
        sound: "drum.mp3",
        description: {
          product:
            "Cmc Indy Series that comes with quality and colors that are very beautiful. Using materials like poplar wood to make a shell drum that resonates clearly, but when listened to, there is a warm heart. Suitable for quite a variety of music styles, along with a snare made of steel that gives a sound that hits the heart. The drum unit is the same as the CMC Prelude, using a single drum unit bolt to enhance the sound performance.",
          brand: "Cmc Indy Series ",
          series: "Cmc Indy Series ",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 44,
        name: "Cmc Indy Series",
        price: 18500,
        quantity: 9,
        type: "drum",
        imageURL: "D8.jpeg",
        sound: "drum.mp3",
        description: {
          product:
            "Cmc Indy Series that comes with quality and colors that are very beautiful. Using materials like poplar wood to make a shell drum that resonates clearly, but when listened to, there is a warm heart. Suitable for quite a variety of music styles, along with a snare made of steel that gives a sound that hits the heart. The drum unit is the same as the CMC Prelude, using a single drum unit bolt to enhance the sound performance.",
          brand: "Cmc Indy Series ",
          series: "Cmc Indy Series ",
          color: "Black,White",
          note: "",
        },
      },
      {
        id: 45,
        name: "Pearl Road Show",
        price: 18000,
        quantity: 9,
        type: "drum",
        imageURL: "D9.jpg",
        sound: "drum.mp3",
        description: {
          product:
            "Pearl Road Show 5-piece drum set that comes with Hardware, Cymble, with a drum body made of poplawood that gives a warm, soft sound, no matter how hard you hit it, the sound will come out sustainably balanced, every edge of the drum is made. From Still provides strength and durability in playing Rim Shot, Rim Knocks, etc., can play comfortably. It also comes with 2 standard Tom Holders Hardwere to adjust the playing angle to suit yourself the most. Also, the provided pedal is a double chain single pedal from Pearl that adds strength and provides higher agility while playing.",
          brand: "Pearl Road Show",
          series: "Pearl Road Show",
          color: "Black,White",
          note: "",
        },
      },
    ]
module.exports = dataProduct;
